### ISSUE TITLE
Request: copy cover.jpg or folder.jpg

### ISSUE THREAD

**Issue by ghost** [SimonPersson/flac2opus#1]
Hi there,

Firstly thanks for script! I guess I don't need to learn to write one now!
It sure does look intimidating that a FLAC to OPUS Bash script would look like this.

As an improvement, the script could also copy folder.jpg as well. This seems simple enough for someone with minimal Bash scripting experience that they could just copy and paste the segment of code referring to cover.jpg and change it to folder.jpg, but for the practice of "clean code", I imagine there would be a better way than just doing that.

**Comment by SimonTeixidor** [comment]
Hi!

>Firstly thanks for script! I guess I don't need to learn to write one now!
It sure does look intimidating that a FLAC to OPUS Bash script would look like this.

The script could without doubt be written in a simpler style. First because I have made some optimizations, using parallel to run on many cores, and diff to only do the minimal amount of work, that makes it a bit less readable. But also because I'm not the greatest shell programmer ever :)

> As an improvement, the script could also copy folder.jpg as well. This seems simple enough for someone with minimal Bash scripting experience that they could just copy and paste the segment of code referring to cover.jpg and change it to folder.jpg, but for the practice of "clean code", I imagine there would be a better way than just doing that.

Done! You could do what you suggested, but I suspect it is quicker, and definitely more maintainable, to use the `-o` switch to find (meaning "or").

I'll close this issue, feel free to reopen if it doesn't work for you :)
